#! /bin/bash
machine=`uname -m`
case "$machine" in
    x86_64)
        myaddr=101
        ;;
    armv7l)
        myaddr=102
        ;;
    *)
        echo "Unknown machine type $machine"
        ;;
esac

fulladdr="2016:bd8:0:f101::$myaddr/64"
echo "Setting tun0 address $fulladdr"

# first create the tun device
ip tuntap add mode tun
# now assign an address to tun0
ip -6 addr add $fulladdr dev tun0 nodad
# bring up the link
ip -6 link set dev tun0 up
