#! /bin/bash
# derive OUI-64 from OUI-48 from first Ethernet port
ethmac=`ip link show | awk '/ether/{print $2; exit}' | awk 'BEGIN {FS=":"; OFS=""}{print $1 $2, $3 "fffe" $4, $5 $6}'` 
echo ${ethmac}
until pids=$(pidof wisund)
do 
	sleep 1
done
## give the driver enough time to begin accepting connections
sleep 3
echo setmac ${ethmac} > /dev/tcp/localhost/5555
echo nlbr > /dev/tcp/localhost/5555
